apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xpodidentities.aws.hops.ops.com.ai
spec:
  group: aws.hops.ops.com.ai
  names:
    categories:
      - crossplane
    kind: XPodIdentity
    plural: xpodidentities
  scope: Cluster
  versions:
    - name: v1alpha1
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: XPodIdentity defines an AWS IAM role and EKS Pod Identity association.
          properties:
            spec:
              type: object
              description: XPodIdentitySpec defines the desired state.
              properties:
                parameters:
                  type: object
                  description: PodIdentity configuration parameters.
                  properties:
                    region:
                      type: string
                      description: AWS region hosting the EKS cluster.
                    clusterName:
                      type: string
                      description: Name of the cluster to bind the pod identity association to.
                    clusterNameRef:
                      type: object
                      description: Reference to a Cluster in eks to populate clusterName.
                      properties:
                        name:
                          type: string
                          description: Name of the referenced object.
                        policy:
                          type: object
                          description: Policies for referencing.
                          properties:
                            resolution:
                              type: string
                              description: |
                                Resolution specifies whether resolution of this reference is required.
                                The default is 'Required', which means the reconcile will fail if the
                                reference cannot be resolved. 'Optional' means this reference will be
                                a no-op if it cannot be resolved.
                              default: Required
                              enum:
                                - Required
                                - Optional
                            resolve:
                              type: string
                              description: |
                                Resolve specifies when this reference should be resolved. The default
                                is 'IfNotPresent', which will attempt to resolve the reference only when
                                the corresponding field is not present. Use 'Always' to resolve the
                                reference on every reconcile.
                              enum:
                                - Always
                                - IfNotPresent
                      required:
                        - name
                    clusterNameSelector:
                      type: object
                      description: Selector for a Cluster in eks to populate clusterName.
                      properties:
                        matchControllerRef:
                          type: boolean
                          description: |
                            MatchControllerRef ensures an object with the same controller reference
                            as the selecting object is selected.
                        matchLabels:
                          type: object
                          description: MatchLabels ensures an object with matching labels is selected.
                          additionalProperties:
                            type: string
                        policy:
                          type: object
                          description: Policies for selection.
                          properties:
                            resolution:
                              type: string
                              description: |
                                Resolution specifies whether resolution of this reference is required.
                                The default is 'Required', which means the reconcile will fail if the
                                reference cannot be resolved. 'Optional' means this reference will be
                                a no-op if it cannot be resolved.
                              default: Required
                              enum:
                                - Required
                                - Optional
                            resolve:
                              type: string
                              description: |
                                Resolve specifies when this reference should be resolved. The default
                                is 'IfNotPresent', which will attempt to resolve the reference only when
                                the corresponding field is not present. Use 'Always' to resolve the
                                reference on every reconcile.
                              enum:
                                - Always
                                - IfNotPresent
                    providerConfigName:
                      type: string
                      description: Crossplane ProviderConfig to use for provisioning these resources.
                    deletionPolicy:
                      type: string
                      description: Delete or orphan external resources when the XR is deleted. Defaults to Delete.
                      enum:
                        - Delete
                        - Orphan
                      default: Delete
                    serviceAccount:
                      type: object
                      description: Target Kubernetes service account.
                      properties:
                        name:
                          type: string
                          description: Name of the Kubernetes service account.
                        namespace:
                          type: string
                          description: Namespace containing the Kubernetes service account.
                      required:
                        - name
                        - namespace
                    inlinePolicy:
                      type: array
                      description: Exclusive set of IAM inline policies to associate with the role.
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Friendly name for the inline policy document.
                          policy:
                            type: string
                            description: Policy document formatted as a JSON string.
                    managedPolicyArns:
                      type: array
                      description: Exclusive set of managed policy ARNs to attach to the IAM role.
                      items:
                        type: string
                      x-kubernetes-list-type: set
                    permissionsBoundaryArn:
                      type: string
                      description: ARN of the permissions boundary policy to apply to the IAM role.
                    roleName:
                      type: string
                      description: Name to apply to the IAM role resource in AWS.
                    tags:
                      type: object
                      description: Additional AWS tags to merge with the default hops tag.
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                    - serviceAccount
              required:
                - parameters
            status:
              type: object
              description: XPodIdentityStatus defines the observed state.
              properties:
                podIdentity:
                  type: object
                  description: Freeform field containing status information for the pod identity association.
                  x-kubernetes-preserve-unknown-fields: true
          required:
            - spec
      served: true
