apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: configuration-aws-eks-pod-identity
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-eks
    version: '>=v2.1.1'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam
    version: '>=v2.1.1'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.5.1'
  description: XRD for configuring AWS Pod Identity associations for service accounts.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # configuration-aws-eks-pod-identity

    Provisions IAM roles, policies, and Amazon EKS Pod Identity associations for Kubernetes service accounts.
  repository: ghcr.io/hops-ops/configuration-aws-eks-pod-identity
  source: github.com/hops-ops/configuration-aws-eks-pod-identity
