apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: podidentities.aws.hops.ops.com.ai
spec:
  group: aws.hops.ops.com.ai
  names:
    categories:
      - crossplane
    kind: PodIdentity
    plural: podidentities
  scope: Namespaced
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          description: PodIdentity defines an AWS IAM role and EKS Pod Identity association.
          properties:
            spec:
              type: object
              description: PodIdentitySpec defines the desired state.
              properties:
                region:
                  type: string
                  description: AWS region hosting the EKS cluster.
                labels:
                  type: object
                  description: Custom labels applied to all Kubernetes resources. Merged with default labels (hops.ops.com.ai/managed, hops.ops.com.ai/podidentity).
                  additionalProperties:
                    type: string
                  x-kubernetes-preserve-unknown-fields: true
                clusterName:
                  type: string
                  description: Name of the cluster to bind the pod identity association to.
                clusterNameRef:
                  type: object
                  description: Reference to a Cluster in eks to populate clusterName.
                  properties:
                    name:
                      type: string
                      description: Name of the referenced object.
                    policy:
                      type: object
                      description: Policies for referencing.
                      properties:
                        resolution:
                          type: string
                          description: |
                            Resolution specifies whether resolution of this reference is required.
                            The default is 'Required', which means the reconcile will fail if the
                            reference cannot be resolved. 'Optional' means this reference will be
                            a no-op if it cannot be resolved.
                          default: Required
                          enum:
                            - Required
                            - Optional
                        resolve:
                          type: string
                          description: |
                            Resolve specifies when this reference should be resolved. The default
                            is 'IfNotPresent', which will attempt to resolve the reference only when
                            the corresponding field is not present. Use 'Always' to resolve the
                            reference on every reconcile.
                          enum:
                            - Always
                            - IfNotPresent
                  required:
                    - name
                clusterNameSelector:
                  type: object
                  description: Selector for a Cluster in eks to populate clusterName.
                  properties:
                    matchControllerRef:
                      type: boolean
                      description: |
                        MatchControllerRef ensures an object with the same controller reference
                        as the selecting object is selected.
                    matchLabels:
                      type: object
                      description: MatchLabels ensures an object with matching labels is selected.
                      additionalProperties:
                        type: string
                    policy:
                      type: object
                      description: Policies for selection.
                      properties:
                        resolution:
                          type: string
                          description: |
                            Resolution specifies whether resolution of this reference is required.
                            The default is 'Required', which means the reconcile will fail if the
                            reference cannot be resolved. 'Optional' means this reference will be
                            a no-op if it cannot be resolved.
                          default: Required
                          enum:
                            - Required
                            - Optional
                        resolve:
                          type: string
                          description: |
                            Resolve specifies when this reference should be resolved. The default
                            is 'IfNotPresent', which will attempt to resolve the reference only when
                            the corresponding field is not present. Use 'Always' to resolve the
                            reference on every reconcile.
                          enum:
                            - Always
                            - IfNotPresent
                providerConfigRef:
                  type: object
                  description: Reference to the ProviderConfig for AWS resources. Defaults to clusterName or "default" when unset.
                  properties:
                    name:
                      type: string
                      description: Name of the ProviderConfig.
                    kind:
                      type: string
                      description: Kind of the ProviderConfig. Defaults to ProviderConfig.
                      default: ProviderConfig
                managementPolicies:
                  description: ManagementPolicies for AWS resources. Defaults to ["*"] which includes all operations (Create, Observe, Update, Delete, LateInitialize). To orphan resources on deletion, use ["Create", "Observe", "Update", "LateInitialize"].
                  type: array
                  items:
                    type: string
                    enum:
                      - "*"
                      - Create
                      - Observe
                      - Update
                      - Delete
                      - LateInitialize
                  default:
                    - "*"
                serviceAccount:
                  type: object
                  description: Target Kubernetes service account.
                  properties:
                    name:
                      type: string
                      description: Name of the Kubernetes service account.
                    namespace:
                      type: string
                      description: Namespace containing the Kubernetes service account.
                  required:
                    - name
                    - namespace
                inlinePolicy:
                  type: array
                  description: Exclusive set of IAM inline policies to associate with the role.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Friendly name for the inline policy document.
                      policy:
                        type: string
                        description: Policy document formatted as a JSON string.
                managedPolicyArns:
                  type: array
                  description: Exclusive set of managed policy ARNs to attach to the IAM role.
                  items:
                    type: string
                  x-kubernetes-list-type: set
                permissionsBoundaryArn:
                  type: string
                  description: ARN of the permissions boundary policy to apply to the IAM role.
                rolePrefix:
                  type: string
                  description: Prefix prepended to the generated IAM role name when roleNameOverride is not set.
                roleNameOverride:
                  type: string
                  description: Explicit IAM role name override. When set, this value is used instead of the generated name or prefix.
                role:
                  type: object
                  description: IAM role configuration for import scenarios.
                  properties:
                    externalName:
                      type: string
                      description: External name of existing IAM role to import. Leave empty to create new. The external name is the role name (not ARN).
                association:
                  type: object
                  description: Pod Identity Association configuration for import scenarios.
                  properties:
                    externalName:
                      type: string
                      description: External name of existing Pod Identity Association to import. Leave empty to create new. Format is the association ID.
                tags:
                  type: object
                  description: Custom tags applied to all AWS resources. Merged with default tags (hops.ops.com.ai/managed, hops.ops.com.ai/podidentity).
                  additionalProperties:
                    type: string
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - region
                - serviceAccount
                - managementPolicies
            status:
              type: object
              description: PodIdentityStatus defines the observed state.
              properties:
                podIdentity:
                  type: object
                  description: Freeform field containing status information for the pod identity association.
                  x-kubernetes-preserve-unknown-fields: true
          required:
            - spec
