apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: XPodIdentity
metadata:
  name: example
spec:
  parameters:
    clusterName: cluster-x
    region: us-west-2
    serviceAccount:
      namespace: observability
      name: loki
    inlinePolicy:
      - name: default
        policy: |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Action": [
                          "s3:GetObject"
                      ],
                      "Resource": [
                          "arn:aws:s3:::example-loki-chunks/*"
                      ]
                  }
              ]
          }
